version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo:/data/db
    ports:
      - "6000:27017"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  # server:
  #   image: "node:19-alpine"
  #   build: ./
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./:/app
  #   command: ts-node-dev --respawn --respawn --watch -r tsconfig-paths/register --poll src/app.ts
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo
  #     - redis
volumes:
  # data:
  #   driver: local
  mongo:
  redis:
